name: Build release

on: 
  push:
     tags: 
       - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          if [ "${{ matrix.goos }}" = "windows" ]; then
            go build -ldflags="-s -w" -o "build/zkpaste-${{ matrix.goos }}-${{ matrix.goarch }}.exe"
          else 
            go build -ldflags="-s -w" -o "build/zkpaste-${{ matrix.goos }}-${{ matrix.goarch }}"
          fi
           
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          path: build/*
          name: binaries
          
    
