name: Build release

permissions:
  contents: write

on: 
  push:
     tags: 
       - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          if [ "${{ matrix.goos }}" = "windows" ]; then
            go build -ldflags="-s -w" -o "build/zkpaste.exe"
          else 
            go build -ldflags="-s -w" -o "build/zkpaste"
          fi
        
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          path: build/*
          name: "${{ matrix.goos }}-${{ matrix.goarch }}"
  
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: builds
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{github.workspace}}/builds/*/*
          generate_release_notes: true
          draft: true
      
    
    
